# ３章 データ構造 

## 3.2 numPy

### 3.2.1　NumPyの関数

In [16]:
python_2d_list =[[1, 3, 5], [2, 4, 6], [7, 9, 11]]

In [17]:
first_column = [python_2d_list[i][0] for i in range(len(python_2d_list))]

In [18]:
first_column

[1, 2, 7]

In [19]:
import numpy as np

np_2d_array = np.array([[1, 3, 5], [2, 4, 6], [7, 9, 11]])

first_column = np_2d_array[:, 0]

In [20]:
first_column

array([1, 2, 7])

### 3.2.2　NumPyのパフォーマンスに関する考察

In [21]:
mixed_type_list = ["one", 2, 3.14]

In [22]:
mixed_type_array = np.array(["one", 2, 3.14])

In [23]:
print(mixed_type_array)

['one' '2' '3.14']


In [24]:
integer_array = np.array([1, 2, 3])
print(integer_array.dtype)

int64


##### ●Pythonのリストと比較して、NumPyを使うことでパフォーマンスが向上する例

In [25]:
random_int_array = np.random.randint(1, 100_000, 100_000)
random_int_list = list(random_int_array)

In [26]:
%%timeit -r 7 -n 100
sum(random_int_list)

1.76 ms ± 59.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
%%timeit -r 7 -n 100
np.sum(random_int_array)


12.1 μs ± 2.41 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##### ●配列を適切なスペースで初期化する

In [28]:
array_to_fill = np.zeros(1000)

In [29]:
random_int_array = np.random.randint(1, 100_000, 100_000)

In [30]:
random_int_array.nbytes

800000

In [31]:
random_int_array.dtype

dtype('int64')

In [32]:
random_int_array_32 = random_int_array.astype(np.int32)

In [33]:
random_int_array_32.nbytes

400000

In [34]:
small_array = np.array([1, 3, 5], dtype=np.int16)

In [35]:
small_array.dtype

dtype('int16')

### 3.2.3　Daskを使った配列演算

##### ●環境によってはすごく時間がかかるかもしれないので、注意。30億 -> 10億でよいかも

In [1]:
import numpy as np
large_np_array = np.random.randint(1, 100000, 30_0000_0000)

In [2]:
%%timeit -r 1 -n 7
np.max(large_np_array)

6.35 s ± 0 ns per loop (mean ± std. dev. of 1 run, 7 loops each)


In [3]:
import dask.array as da

large_np_array = np.random.randint(1, 100000, 30_0000_0000)

In [4]:
large_dask_array = da.from_array(large_np_array)

In [45]:
%%timeit -r 1 -n 7
array_max = large_dask_array.max()
array_max.compute()

4.39 s ± 0 ns per loop (mean ± std. dev. of 1 run, 7 loops each)


In [5]:
array_max = large_dask_array.max()

In [6]:
%%time
array_max.compute()

CPU times: user 1.31 s, sys: 13.4 s, total: 14.7 s
Wall time: 4.4 s


np.int64(99999)

In [1]:
from dask.distributed import Client

client = Client(n_workers=4)

In [3]:
client

Connection method: Cluster object,Cluster type: distributed.LocalCluster
Dashboard: http://127.0.0.1:8787/status,
Dashboard: http://127.0.0.1:8787/status,Workers: 4
Total threads: 12,Total memory: 32.00 GiB
Status: running,Using processes: True
Comm: tcp://127.0.0.1:58784,Workers: 0
Dashboard: http://127.0.0.1:8787/status,Total threads: 0
Started: 8 minutes ago,Total memory: 0 B
Comm: tcp://127.0.0.1:58796,Total threads: 3
Dashboard: http://127.0.0.1:58800/status,Memory: 8.00 GiB
Nanny: tcp://127.0.0.1:58787,


### 3.3 機械学習における配列

In [9]:
import numpy as np

np_tensor = np.random.rand(4,4)

In [10]:
np_tensor

array([[0.05751854, 0.90090351, 0.42867323, 0.28850905],
       [0.64892238, 0.05873513, 0.87582391, 0.89069449],
       [0.76038317, 0.96535135, 0.03324167, 0.247393  ],
       [0.06658472, 0.32494639, 0.03871946, 0.82843642]])

##### メモ： 「`pip install tensorflow`」でインストール

In [11]:
import tensorflow as tf

tf_tensor = tf.convert_to_tensor(np_tensor)

In [12]:
tf_tensor

<tf.Tensor: shape=(4, 4), dtype=float64, numpy=
array([[0.05751854, 0.90090351, 0.42867323, 0.28850905],
       [0.64892238, 0.05873513, 0.87582391, 0.89069449],
       [0.76038317, 0.96535135, 0.03324167, 0.247393  ],
       [0.06658472, 0.32494639, 0.03871946, 0.82843642]])>

##### メモ： 「`pip install torch`」でインストール

In [13]:
import torch

pytorch_tensor = torch.from_numpy(np_tensor)

In [14]:
pytorch_tensor

tensor([[0.0575, 0.9009, 0.4287, 0.2885],
        [0.6489, 0.0587, 0.8758, 0.8907],
        [0.7604, 0.9654, 0.0332, 0.2474],
        [0.0666, 0.3249, 0.0387, 0.8284]], dtype=torch.float64)